### ISSUE TITLE
The demo and manual links are down

### ISSUE THREAD

**Issue by victoriousgaming** [xmpp-ftw/xmpp-ftw#121]
Hi

I wanted to check this out in more detail but the demo and manual links are down right now.

Thanks very much.

Will Ferrer

**Comment by lloydwatkin** [comment]
Sorry, I'd missed this! Looks like nodejitsu finally died. I'll try and get this pushed up on another host ASAP.

**Comment by lloydwatkin** [comment]
See https://xmpp-ftw.herokuapp.com/
