### ISSUE TITLE
How do I set the URL of my XMPP server which is in the cloud vs XMPP-FTW at localhost?

### ISSUE THREAD

**Issue by marcusegues** [xmpp-ftw/xmpp-ftw#173]
I understand that XMPP-FTW is a node.js server sitting between my client code and my XMPP server. I have a Prosody XMPP server running in the cloud, and I have my client and my XMPP-FTW server code on my localhost machine. 

I am following along the book `Practical XMPP` but it assumes everything is installed on localhost. 

Where is it that I set the address of the XMPP server, so that when I send a message such as 'xmpp.login' from my client to the XMPP-FTW server, the latter will route this over to my XMPP server in the cloud? Do I need to have any code on my XMPP server? I thought that the XMPP-FTW code would send XML to my XMPP server, and receive XML from that server, translate it to JSON and then pass this along to my client. Is this the case?

**Comment by lloydwatkin** [comment]
The server is determined from the domain part of your jid, e.g. marcus@**github.com** would do a look up for the XMPP server on github.com. If you are running the XMPP server on a specific host and don't have the DNS set up correctly then you can pass a `host` parameter during login.

No special code required on your XMPP server, XMPP-FTW is essentially an XMPP client itself.

> I thought that the XMPP-FTW code would send XML to my XMPP server, and receive XML from that server, translate it to JSON and then pass this along to my client. Is this the case?

:+1:

**Comment by marcusegues** [comment]
I am specifically following Chapter 4 of `Practical XMPP`. 

Quick recap of what this means:
I have an `index.js` file which sets up a local http server, sets up a Primus instance using the server and `websockets` transformer, I use the `primus-emitter` plugin on my `primus` instance, and generate the primus client-side code in a `scripts` folder. My served `index.html` creates a new Primus socket, and based on the generated client-side code it will connect to my server. At this point there is not XMPP-FTW yet.

When the client does establish the socket connection to my http server, then we get the XMPP-FTW instance created.

My client also loads a script called `xmpp.js` which defines some callbacks for specific standard XMPP-FTW events on the socket, such as `xmpp.connection`. 

**Now to my still present issue:**
On my client, I can input a `login` (full JID from my own XMPP Prosody XMPP server in the cloud) and `password`, and click login, which executes something like:
```
  var options = {
    jid: jid,
    password: mypassword,
    host: 'my.xmpp.server',
  };
  socket.send('xmpp.login', options);
```

 I can see in my Prosody log that it does log me in when I click `login`. However, the `xmpp.connection` event is not emitted on my client-side code.

I my terminal I see the following debugging information:
```
New websocket connection
  xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +0ms
  xmpp:connection use lazy socket +2ms
  xmpp:connection setup stream +2ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="my.xmpp.server"> +206ms
  xmpp:connection receive: <?xml version='1.0'?><stream:stream xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en' from='my.xmpp.server' id='675c2b6e-f1bc-4efc-9a63-e2f1caab807a' version='1.0' xmlns='jabber:client'><stream:features><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/><c hash='sha-1' ver='ZBWApSGFMsTZkuVThHtyU5xv1Mk=' node='http://prosody.im' xmlns='http://jabber.org/protocol/caps'/><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>SCRAM-SHA-1</mechanism></mechanisms></stream:features> +9ms
  xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +4ms
  xmpp:connection receive: <proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/> +10ms
  xmpp:connection use standard socket +15ms
  xmpp:connection setup stream +0ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="my.xmpp.server"> +29ms
  xmpp:connection receive: <?xml version='1.0'?><stream:stream xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en' from='my.xmpp.server' id='2b818e44-a51f-447c-890d-2ac3c86a29d7' version='1.0' xmlns='jabber:client'><stream:features><c hash='sha-1' ver='ZBWApSGFMsTZkuVThHtyU5xv1Mk=' node='http://prosody.im' xmlns='http://jabber.org/protocol/caps'/><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>SCRAM-SHA-1-PLUS</mechanism></mechanisms></stream:features> +10ms
  xmpp:connection send: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">bWFyY3VzQHNpcHB5LmR1Y2tkbnMub3JnAG1hcmN1cwBwYXNzd29yZA==</auth> +2ms
  xmpp:connection receive: <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/> +10ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="my.xmpp.server"> +1ms
  xmpp:connection receive: <?xml version='1.0'?><stream:stream xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en' from='my.xmpp.server' id='b7a4c067-9874-4838-84b3-dfa99ebf47ad' version='1.0' xmlns='jabber:client'><stream:features><ver xmlns='urn:xmpp:features:rosterver'/><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><required/></bind><session xmlns='urn:ietf:params:xml:ns:xmpp-session'><optional/></session></stream:features> +10ms
  xmpp:connection send: <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/> +1ms
  xmpp:connection receive: <iq id='bind' type='result'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><jid>marcus@my.xmpp.server/21acc9dc-1b0f-46fe-a98c-61b7782ed93c</jid></bind></iq> +9ms
  xmpp:connection send: <session xmlns="urn:ietf:params:xml:ns:xmpp-session"/> +2ms
  xmpp:connection receive: <iq id='sess' type='result' to='marcus@my.xmpp.server/21acc9dc-1b0f-46fe-a98c-61b7782ed93c' from='my.xmpp.server'/> +10ms
```

I can open an Adium XMPP client, and log in to my XMPP server as well. From my own client, I can type a message in a `textarea` and send to this Adium client, and the latter does receive the message. I can then reply to the message, from the Adium client to my own client. I have this code in my `xmpp.js`:
```
socket.on('xmpp.chat.message', function(incoming) {
  console.log('Incoming');
})
```
My callback above does not get called. However, in my terminal, I see that 

```
xmpp:connection receive: <message id='purplee496fb37' type='chat' to='marcus@my.xmpp.server/64e9f043-3184-4d7e-aeec-aa65e4b4168c' from='mary@my.xmpp.server/mbp-pr'><active xmlns='http://jabber.org/protocol/chatstates'/><body>Hi there!</body></message>
```

So my own client does indeed receive the message, but why aren't the XMPP-FTW events being fired?

**Comment by lloydwatkin** [comment]
Ok, if you open up developer tools and monitor the websocket connection, are you seeing the data arrive at the browser (if not the problem will be at the xmpp-ftw server).

If the `xmpp.connection` event isn't firing then none of the callbacks will be registered in order to receive your messages actually. So we'll need to look at that.

does your set up work here: https://xmpp-ftw.herokuapp.com/demo/ ?

**Comment by marcusegues** [comment]
Do you mean if I can successfully communicate with my XMPP server using the demo? Yes I can.

Ok, I've inspected the websocket frames, and I am indeed getting an 'xmpp.connection' message. 

In my `xmpp.js` I had:

```
socket.on('xmpp.connection', connected);
var connected = function(details) {
  console.log('connected');
  $('p.connection-status').html('Online');
};
```

I switched the order of those statements and it worked, i.e., defined `connected` before passing it as a callback. I switched the order for the other event handlers as well, so now I am successfully logging in and sending messages.

One further question: in the documentation, there is a section entitled `Server-side` with the text `If you want to run xmpp-ftw server side (e.g. to write a bot) then this should be a good starting point:`. 

What is this code for exactly? There is no explanation accompanying that code.

**Comment by lloydwatkin** [comment]
\o/

Basically if you want to work with XMPP server side but not learn how to use XMPP if you already know XMPP-FTW then you can use that code to set up XMPP-FTW server side.

**Comment by marcusegues** [comment]
So in the case of having a browser client, an XMPP-FTW node.js server, and a separate XMPP server, when you say 'server-side' you're referring to just having an extra server that would be able to handle incoming stanzas using
