### ISSUE TITLE
How do I use with socket.io instead of Primus?

### ISSUE THREAD

**Issue by marcusegues** [xmpp-ftw/xmpp-ftw#174]
As I understand, we set up a node.js server to listen for socket.io connections. Something like this: 
```
const app = require('express'),
  server = require('http').Server(app),
  io = require('socket.io')(server),
  Xmpp = require('xmpp-ftw'),
  Disco = require('xmpp-ftw-disco'),
  Muc = require('xmpp-ftw-muc');

server.listen(5000, function() {
  console.log('XMPP-FTW listening on port %d', server.address().port);
});

io.sockets.on('connection', socket => {
  const xmpp = new Xmpp.Xmpp(socket);
  socket.xmpp = xmpp;

  socket.on('disconnect', () => {
    console.log(
      `A client just disconnected, there are ${io.engine.clientsCount} clients.`
      socket.xmpp.logout();
    );
  });
});
```

The client simply has to connect:
```
import SocketIOClient from 'socket.io-client';

const createXmppFtwSocket = () => {
  const socket = SocketIOClient('http://localhost:5000', {
    transports: ['websocket'],
  });
  return Promise.resolve(socket);
};

createXmppFtwSocket().then(socket => {
     socket.on('connect', () => {
      console.log('Connected to XMPP-FTW server.');
    });

    socket.on('xmpp.connection', data => {
      console.log('Connected as', data.jid);
    });

    console.log('Logging in to XMPP server', name);
    const options = {
      jid: `me@my.xmpp.server`,
      password: 'password',
      host: 'my.xmpp.server',
    };
    this.xmppFtwSocket.send('xmpp.login', options);
})
```

The above creates the socket.io connection from client to XMPP-FTW server, then defines some event handlers for the custom XMPP-FTW events like 'xmpp.connection' which is fired when we get logged in. Then, the client actually sends the message to login. This is not working, as the event 'xmpp.connection' is not firing.

**Is this the correct way to do this with socket.io?**

**Comment by marcusegues** [comment]
To get the above code working I had to use `xmppFtwSocket.emit` instead of `xmppFtwSocket.send`.

**Comment by lloydwatkin** [comment]
You can also use socket.io as a backend for primus. Primus is an excellent websocket library abstraction layer :)

**Comment by marcusegues** [comment]
I am trying to use XMPP-FTW in a React application, and I didn't really understand how I would best use the Primus generated client code in my React app. That's why I switched to socket.io at this stage. Maybe when I figure it out I'll switch back.

**Comment by lloydwatkin** [comment]
Primus isn't really that different to socket.io in terms of API. If you get really stuck at any point please do let me know :)
