### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by triniwiz** [xmpp-ftw/xmpp-ftw#86]
I can't seem to get socket.io to use  xmpp-ftw 

my server code 

var express = require('express')
    , xmppFtw = require('xmpp-ftw')
    , winston = require('winston')
    , http = require('http');

var app = express();
var server = app.listen(3000);
var io = require('socket.io').listen(server,{

    logger: {
        debug: winston.debug,
        info: winston.info,
        error: winston.error,
        warn: winston.warn
    }

});

io.sockets.on('connection', function (socket) {

    new xmppFtw.Xmpp(socket);

    console.log('A new user connected!');
    //socket.emit('info', { msg: 'The world is round, there is no up or down.' });

});

i used new xmppFtw.Xmpp(socket); because  new require('xmpp-ftw').Xmpp(socket);  is throwing some error then crashing the the nodejs server instance

my client code  : - 

 <script src="http://localhost:3000/socket.io/socket.io.js"></script>

<script>
    var socket = io.connect('http://localhost:3000')

    socket.on('error', function(error) { console.log(error) } )

    socket.on('connect', function(data) {
        console.log('connected', data)
    })

    socket.on('connect.fail', function(reason) {
        console.log('Connection failed: ' + reason)
    })

    socket.on('disconnect', function() {
    })

    socket.on('xmpp.connection', function(status) {
        log('Connection status is: ' + status)
    })

    socket.on('xmpp.message.chat', function(data) {
        console.log('Received a chat from: ' + data.from)
        console.log('Content was: ' + data.content)
    })

    socket.on('xmpp.presence', function(data) {
        console.log('Presence update from: ' + data.from)
        console.log('Availability: ' + data.status)
        console.log(data.message)
    })

</script>

when ever i try ->  socket.send('xmpp.login',{"jid":"test@localhost","password":"test123"})

i get this response - > Socket {io: Manager, nsp: "/", json: Socket, ids: 0, acks: Object…}

:/ can anyone tell me what i'm not doing correct because i'm a bit tired of banging my head on this wall  

one more thing do i need to user primus with socket.io or i can use socket.io alone

**Comment by triniwiz** [comment]
I got it working and want share my config so if any newbie like myself comes across the problem


server config 


'use strict';
var xmpp = require('xmpp-ftw')
var Primus = require('primus')
    , http = require('http');


var server = http.createServer();
var app = new Primus(server,


{
    transformer: 'engine.io',
        parser: 'JSON',
    transports: [
    'websocket',
    'htmlfile',
    'xhr-polling',
    'jsonp-polling'
]
}

);

app
    .use('emitter', 'primus-emitter');


server.listen(3000);


var Muc = require('xmpp-ftw-muc')
var Disco = require('xmpp-ftw-disco')
var Pubsub = require('xmpp-ftw-pubsub')
var Register = require('xmpp-ftw-register')
var Avatar = require('xmpp-ftw-avatar')
var Search = require('xmpp-ftw-search')
var Rpc = require('xmpp-ftw-rpc')
var Jingle = require('xmpp-ftw-jingle')
var Ping = require('xmpp-ftw-ping')



app.on('connection', function (socket) {
   console.log('user connected');

    var xmppFtw = new xmpp.Xmpp(socket)
    xmppFtw.addListener(new Muc())
    xmppFtw.addListener(new Disco())
    xmppFtw.addListener(new Pubsub())
    xmppFtw.addListener(new Register())
    xmppFtw.addListener(new Avatar())
    xmppFtw.addListener(new Search())
    xmppFtw.addListener(new Rpc())
    xmppFtw.addListener(new Jingle())
    xmppFtw.addListener(new Ping())
    socket.xmppFtw = xmppFtw


});


 <script src="http://localhost:3000/primus/primus.js"></script>

<script>
    var socket = new Primus('http://localhost:3000', {  });

    socket.on('error', function(error) { console.log(error) } )

    socket.on('connect', function() {
        console.log('connected')


    })

    socket.on('connect.fail', function(reason) {
        console.log('Connection failed: ' + reason)
    })

    socket.on('disconnect', function() {
    })

    socket.on('xmpp.connection', function(status) {
        console.log(JSON.stringify(status))
        console.log(status.status)

     //   if(status.status == 'online'){

            socket.send('xmpp.presence' , {"show":"online"} )
      //  }



    })
    socket.on('xmpp.error', function(error) { console.log(error) } )

    socket.on('xmpp.chat.message', function(data) {
        console.log(data)
    })

    socket.on('xmpp.presence', function(data) {
        console.log(data);
    })
    socket.on('xmpp.presence.error', function(data) {
        console.log(data);
    })
    socket.on('xmpp.presence.subscribe', function(data) {
        console.log(data)
    })
    socket.on('xmpp.roster.push', function(data) {
        console.log(data);
    })


</script>

**Comment by lloydwatkin** [comment]
Hi @triniwiz,

I'm not entirely sure what you issue is here, but glad you've got a project working for yourself. Here's a useful project to get you started with xmpp-ftw and a websocket connection: https://github.com/xmpp-ftw/skeleton-project

Lloyd

**Comment by triniwiz** [comment]
Thanks
