### ISSUE TITLE
how to set XEP-0080 data into a pubsub node?

### ISSUE THREAD

**Issue by robotnic** [xmpp-ftw/xmpp-ftw#88]
I found to nodes:
geo/next
geo/current
geo/previous

What's the json format for lat,lng,city,....?

If I have to invent a format it would look like:
```
{
type:"Feature"
geometry:{
   point:[16.4,48.2],
},
properties:{
       city:"Vienna",
       country:"Austria",
       ...
   }
}

```
http://geojson.org/

**Comment by lloydwatkin** [comment]
I believe it uses http://xmpp.org/extensions/xep-0080.html but you'd need to extend xmpp-ftw/xmpp-ftw-item-parser to support this format.
