### ISSUE TITLE
Install problem with new setup

### ISSUE THREAD

**Issue by timpisti** [xmpp-ftw/xmpp-ftw#89]
Windows 8.1, installed python & VS Express

...\node_modules\xmpp-ftw\node_modules\node-xmpp-core\node_modules\
node-stringprep\build\node_stringprep.vcxproj(47,50): error MSB4025: The project file could not be loaded. Invalid character in the given encoding. Line 47, position 50.
gyp ERR! build error

**Comment by lloydwatkin** [comment]
Your problem here is with `node-stringprep` and not `xmpp-ftw`. My suggestion would be that you need to install the `libicu` libraries.
