### ISSUE TITLE
Constrain history revision 

### ISSUE THREAD

**Issue by TameOfGroans** [xmpp-ftw/xmpp-ftw#90]
Ability to change (or delete) item in friend's chat history. 

A better xep would allow one to require this enabled by friends it order to chat much like one may require OTR

**Comment by TameOfGroans** [comment]
Constrain = conversation

**Comment by lloydwatkin** [comment]
Hi @TameOfGroans, if you have a suggestion for modifying chat history then I suggest you email the [jdev](http://mail.jabber.org/mailman/listinfo/jdev) mailing list (or join the jdev muc) and get a discussion going :)
