### ISSUE TITLE
A general connection question - not an issue

### ISSUE THREAD

**Issue by pateljatin** [xmpp-ftw/xmpp-ftw#93]
Hi,

I have a general connection question to an xmpp server from node server using xmpp-ftw. Here's what I'm doing:

Connect mobile apps to node app server using http/rest calls and then node-app-server connects to ejabberd xmpp server. meaning all communication from mobile chat apps only goes to node app server and then node app server sends them over to ejabberd.
So, how would xmpp-ftw library make a connection to xmpp server and process all user registrations, send chat messages, manage rosters and so on. Note that these are native mobile apps using http/RESTful calls with JSON payload. 

Any hints or help would be greatly appreciated. I read your blog and thought process on how you hacked this together - great job!!

Thanks,
Jatin

**Comment by pateljatin** [comment]
Also which xmpp server did you use for your demo? Was it ejabberd? Or something else? And how did you connect the two servers?

Thanks!

**Comment by lloydwatkin** [comment]
The demo runs against buddycloud.org which runs Prosody but I also run regularly against Tigase too. Once DNS and certificates are set up you don't have to do anything special for server to server (s2s) communications.

XMPP-FTW just uses node-xmpp-client behind the scenes and translates between JSON and XML to make things easier for the user.

What you are trying to do sounds a lot like https://github.com/buddycloud/buddycloud-http-api. I'd suggest taking a look at that as it will answer a lot fo your questions. @imaginator will also be able to provide more information.

**Comment by pateljatin** [comment]
Thanks for your help - much appreciated 
So I installed ejabberd server and enabled http-bind in the config file.  Created two users (john@my-localhost and jane@my-localhost) via ejabberd shell and tested using Adium, etc.
So now to test using code...
Now, on the node.js side - I have following lines based on the example of server-side:
```
var xmppFtw = require('xmpp-ftw')
var Emitter = require('events').EventEmitter

var Socket = function() {
    this.server = new Emitter()
    this.client = new Emitter()
    var self = this
    this.server.send = function(event, data, rsm, callback) {
        self.client.emit(event, data, rsm, callback)
    }
    this.client.send = function(event, data, callback) {
        self.server.emit(event, data, callback)
    }
}
Socket.prototype.on = function(event, data, rsm) {
    this.server.on(event, data, rsm)
}
Socket.prototype.send = function(event, data, callback) {
    this.server.send(event, data, callback)
}
Socket.prototype.removeAllListeners = function(event) {
    this.server.removeAllListeners(event)
}

var socket = new Socket()
var client = new xmppFtw.Xmpp(socket)
socket.client.on('xmpp.connection', function (data) {
    console.log('Connected', data)
})
socket.client.on('xmpp.error', function (error) {
    console.log('error', error)
})
socket.client.on('xmpp.error.client', function (error) {
    console.log('client error', error)
})
socket.client.send('xmpp.login', { login: 'details', here: true })
socket.client.send(
    'xmpp.chat.message',
    {
        to: 'john@my-localhost',
        content: 'Hello world'
    },
    function (error, data) { console.log(error, data) }
)
```
I changed john@my-localhost to one of my user accounts on adium.
I installed xmpp-ftw via npm install

However, when I run server.js (above lines) - I'm getting following error:
```
error { type: 'auth',
  condition: 'client-error',
  description: 'Missing jid and/or password',
  request: { login: 'details', here: true } }
```
error makes sense as I haven't specified connection info anywhere - but where to? :)

Thanks!

**Comment by lloydwatkin** [comment]
1. You don't need http-bind since you are using a socket not BOSH
2. You need to provide login details in the **xmpp.login** call - please see http://xmpp-ftw.jit.su/manual/core/#login

**Comment by pateljatin** [comment]
:) I just went through the manual :-) thank you - so now I have the following.
```
var xmppFtw = require('xmpp-ftw')
var Emitter = require('events').EventEmitter

var Socket = function() {
    this.server = new Emitter()
    this.client = new Emitter()
    var self = this
    this.server.send = function(event, data, rsm, callback) {
        self.client.emit(event, data, rsm, callback)
    }
    this.client.send = function(event, data, callback) {
        self.server.emit(event, data, callback)
    }
}
Socket.prototype.on = function(event, data, rsm) {
    this.server.on(event, data, rsm)
}
Socket.prototype.send = function(event, data, callback) {
    this.server.send(event, data, callback)
}
Socket.prototype.removeAllListeners = function(event) {
    this.server.removeAllListeners(event)
}

var socket = new Socket()
var client = new xmppFtw.Xmpp(socket)
socket.client.on('xmpp.connection', function (data) {
    console.log('Connected', data)
})
socket.client.on('xmpp.error', function (error) {
    console.log('error', error)
})
socket.client.on('xmpp.error.client', function (error) {
    console.log('client error', error)
})
//socket.client.send('xmpp.login', { login: 'details', here: true })
socket.client.send(
    'xmpp.login',
    {
        "jid": "jatin@my-localhost",
        "password": "pass123",
        /* "resource": "xmpp-ftw", */
        "host": "localhost"
    }
)
socket.client.send(
    'xmpp.chat.message',
    {
        to: 'jane@my-localhost',
        content: 'Hello world'
    },
    function (error, data) {
        console.log(error, data)
    }
)
```
and I get the following in the console:
```
Cannot load StringPrep-0.5.4 bindings (using fallback). You may need to `npm install node-stringprep`
createCredentials() is deprecated, use tls.createSecureContext instead
Connected { status: 'online',
  jid: 
   { local: 'jatin',
     domain: 'my-localhost',
     resource: '2317589070143440277775534',
     user: 'jatin' } }
```
So I'm logged in - but I don't see the Hello World message between two adium users - must need more coffee today :(

Thanks!

**Comment by lloydwatkin** [comment]
Make sure you aren't trying to send the IM before you are logged in

**Comment by pateljatin** [comment]
doh me! :)
```
var xmppFtw = require('xmpp-ftw')
var Emitter = require('events').EventEmitter

var Socket = function() {
    this.server = new Emitter()
    this.client = new Emitter()
    var self = this
    this.server.send = function(event, data, rsm, callback) {
        self.client.emit(event, data, rsm, callback)
    }
    this.client.send = function(event, data, callback) {
        self.server.emit(event, data, callback)
    }
}
Socket.prototype.on = function(event, data, rsm) {
    this.server.on(event, data, rsm)
}
Socket.prototype.send = function(event, data, callback) {
    this.server.send(event, data, callback)
}
Socket.prototype.removeAllListeners = function(event) {
    this.server.removeAllListeners(event)
}

var socket = new Socket()
var client = new xmppFtw.Xmpp(socket)
socket.client.on('xmpp.connection', function (data) {
    console.log('Connected', data);
    if (data) {
        console.log("test");
        socket.client.send(
            'xmpp.chat.message',
            {
                to: 'jane@jatin-patel-local',
                content: 'Hello world'
            },
            function (error, data) {
                console.log(error, data)
            }
        )
        socket.client.send(
            'xmpp.chat.message',
            {
                to: 'jatin@jatin-patel-local',
                content: 'Hello Universe'
            },
            function (error, data) {
                console.log(error, data)
            }
        )
    }
})
socket.client.on('xmpp.error', function (error) {
    console.log('error', error)
})
socket.client.on('xmpp.error.client', function (error) {
    console.log('client error', error)
})
//socket.client.send('xmpp.login', { login: 'details', here: true })
socket.client.send(
    'xmpp.login',
    {
        "jid": "jatin@jatin-patel-local",
        "password": "jello123",
        /* "resource": "xmpp-ftw", */
        "host": "localhost"
    }
)
```
response...
```
Cannot load StringPrep-0.5.4 bindings (using fallback). You may need to `npm install node-stringprep`
createCredentials() is deprecated, use tls.createSecureContext instead
Connected { status: 'online',
  jid: 
   { local: 'jatin',
     domain: 'jatin-patel-local',
     resource: '657851511143441290297705',
     user: 'jatin' } }
test
null { id: '16a4765c-e038-4503-b0b0-9d8c057e97d3' }
null { id: '94e36b34-cade-4ac4-ba81-e7cc771e53eb' }
```

Now that's a good test code - need to organize this and get this going for real...so few questions:
1 - any suggestions on how to separate or organize this better? I will have RESTful calls for mobile apis so for example /user/login and /message and so on...so I'm assuming I would wrap these socket.< > calls within these RESTful calls. Or is there a better way to handle this?
2 - for the login - in the real code, this would not be one specific user - so I'm guessing we can pass user record dynamically from the mobile client api call that server receives, and should work?
3 - it doesn't make sense to put xmpp.chat.message inside socket.client.on('xmpp.connection')...call or is that the design?
4 - I did install string-prep but I still get that error message. Is this something I need to worry about?
5 - I'm getting some tls connection message as deprecation warning - any feedback on this issue?

Really appreciate your help here...

Thanks!

**Comment by lloydwatkin** [comment]
4, 5 don't worry for now.
1, 3 is up to you
2 I'd suggest creating some sort of session manager to map a http session
to a socket connection.

Definitely take a look at the buddycloud http api

**Comment by pateljatin** [comment]
Thanks!
Question on all the modules - there's a separate module for few XEPs - such as RPC, MUC, PubSub, etc.  Is this all part of the core library or do I need to use them separately?
By buddycloud http api - do you mean review the structure or use it? unfortunately, we can't use buddycloud service as we need to own the business logic specifically around chat messages.

Thanks!

**Comment by lloydwatkin** [comment]
You could work from a fork of the http server, or use it as an example.

All the modules need to be injected into the core library on use. Take a
look at the code for xmpp-ftw-demo for an example.

**Comment by pateljatin** [comment]
Thanks for your help!
